github: [opensrc0] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]

open_collective: fe-pilot # Replace with a single Open Collective username

custom: https://app.buidlbox.io/buidler/opensrc0 # Replace with a single custom sponsorship URL